//! `branch-name-from-work.ts` — turn model output / prompts into safe branch
//! leaves, recognize Orca's own auto-generated creature names, and build the
//! branch-naming prompt.
//!
//! # Documented divergences (plan Codex decisions — NOT bugs)
//! - **C1 full lowercase.** [`sanitize_branch_slug`] and
//!   [`strip_configured_branch_prefix`] lowercase with `char::to_lowercase()`
//!   (scalar `flat_map`), NOT `to_ascii_lowercase`, *then* apply the ASCII
//!   whitelist. JS `"İ".toLowerCase()` = `i̇` (i + U+0307) → the ASCII filter
//!   keeps `i`; a `to_ascii_lowercase` port would leave `İ` and drop it whole.
//!   Same for U+212A KELVIN → `k`. Pinned in the C1 tests.
//! - **C4 ASCII digit lock.** The `-\d+$` collision-suffix strip is `-[0-9]+$`,
//!   so `Octopus-٢` (Arabic-Indic) is not stripped — matching JS ASCII `\d`.
//! - **C6 char-boundary-safe capitalization.** [`humanize_branch_slug`] mirrors
//!   `charAt(0).toUpperCase() + slice(1)` by upper-casing the first *scalar* and
//!   appending the rest. JS operates on UTF-16 code units, so a lone-surrogate /
//!   astral first char diverges narrowly; the scalar port never panics.

use std::collections::HashSet;
use std::sync::OnceLock;

use regex::Regex;

use crate::js_ws::js_trim;
use crate::marine_creatures::MARINE_CREATURES;

/// `MAX_BRANCH_NAME_WORDS` (`:6`). Post-generation word cap on the branch leaf.
pub const MAX_BRANCH_NAME_WORDS: usize = 4;

/// `CREATURE_NAMES_LOWER` (`:8`): the 552 creature names lowercased, for the
/// recognition gate. The corpus is pure ASCII, so `to_ascii_lowercase` yields the
/// same set as JS `.toLowerCase()`.
fn creature_names_lower() -> &'static HashSet<String> {
    static SET: OnceLock<HashSet<String>> = OnceLock::new();
    SET.get_or_init(|| {
        MARINE_CREATURES
            .iter()
            .map(|name| name.to_ascii_lowercase())
            .collect()
    })
}

/// `-\d+$` (`:27`) as `-[0-9]+$` (C4). One trailing `-<digits>` group, ASCII only.
fn collision_suffix_re() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(r"-[0-9]+$").unwrap())
}

/// Upper-case the first Unicode scalar and append the rest verbatim — the port of
/// `s.charAt(0).toUpperCase() + s.slice(1)` (C6). Empty string → empty string.
pub(crate) fn upper_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
    }
}

/// `normalizeName` (`:10-12`): `trim().toLowerCase()`. JS trim = [`js_trim`]; full
/// lowercase for source fidelity (the membership set is ASCII, so the resulting
/// boolean is identical either way).
fn normalize_name(name: &str) -> String {
    js_trim(name).chars().flat_map(char::to_lowercase).collect()
}

/// `isAutoGeneratedCreatureBranchName` (`:20-29`). True when the leaf is an
/// Orca-picked creature name, optionally with one `-N` collision suffix.
pub fn is_auto_generated_creature_branch_name(branch_leaf: &str) -> bool {
    let normalized = normalize_name(branch_leaf);
    if normalized.is_empty() {
        return false;
    }
    let base = collision_suffix_re().replace(&normalized, "");
    creature_names_lower().contains(base.as_ref())
}

/// `sanitizeBranchSlug` (`:35-45`). Lowercase (C1 full), collapse each run of
/// non-`[a-z0-9]` into a word break, drop empties, cap at `max_words`, join with
/// `-`. `''` when nothing usable remains.
///
/// Equivalent to `.replace(/[^a-z0-9]+/g,'-').split('-').filter(Boolean)`: a run
/// of disallowed chars is a single separator and empty pieces are dropped.
pub fn sanitize_branch_slug(raw: &str, max_words: usize) -> String {
    let lowered: String = raw.chars().flat_map(char::to_lowercase).collect();
    let words: Vec<&str> = lowered
        .split(|c: char| !(c.is_ascii_lowercase() || c.is_ascii_digit()))
        .filter(|w| !w.is_empty())
        .collect();
    if words.is_empty() {
        return String::new();
    }
    words
        .into_iter()
        .take(max_words)
        .collect::<Vec<_>>()
        .join("-")
}

/// `stripConfiguredBranchPrefix` (`:58-77`). Normalize `prefix` the same way a
/// slug is normalized (C1 full lowercase), then drop a leading `<prefixSlug>-`.
/// Prefix-only echo → `''` (caller skips the rename). `None`/`Some("")` prefix →
/// slug unchanged.
pub fn strip_configured_branch_prefix(slug: &str, prefix: Option<&str>) -> String {
    let prefix = match prefix {
        Some(p) if !p.is_empty() => p,
        _ => return slug.to_string(),
    };
    // `.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')`:
    // joining the non-empty alnum words with `-` yields the same normalized slug
    // with no leading/trailing/doubled hyphens.
    let lowered: String = js_trim(prefix)
        .chars()
        .flat_map(char::to_lowercase)
        .collect();
    let prefix_slug = lowered
        .split(|c: char| !(c.is_ascii_lowercase() || c.is_ascii_digit()))
        .filter(|w| !w.is_empty())
        .collect::<Vec<_>>()
        .join("-");
    if prefix_slug.is_empty() {
        return slug.to_string();
    }
    if slug == prefix_slug {
        return String::new();
    }
    let with_hyphen = format!("{prefix_slug}-");
    if slug.starts_with(&with_hyphen) {
        // prefix_slug is `[a-z0-9-]` (ASCII) → byte offset is char-boundary-safe.
        slug[prefix_slug.len() + 1..].to_string()
    } else {
        slug.to_string()
    }
}

/// `humanizeBranchSlug` (`:84-90`). Kebab → space-joined, first scalar upper-cased
/// (C6). `''` for an all-empty slug.
pub fn humanize_branch_slug(slug: &str) -> String {
    let joined = slug
        .split('-')
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join(" ");
    if joined.is_empty() {
        return String::new();
    }
    upper_first(&joined)
}

/// `BranchNameWorkContext` (`:92-98`). Borrowed for ergonomics.
pub struct BranchNameWorkContext<'a> {
    /// The user's first prompt to the agent in this workspace.
    pub first_prompt: &'a str,
    /// The agent's first response, when it has already arrived.
    pub assistant_message: Option<&'a str>,
}

/// `buildBranchNamePrompt` (`:109-130`). Pure string assembly, `\n`-joined. Note
/// the branch wording (`:118-120`): a custom prompt yields `"Generate a git
/// branch name…"` (no "short"), the default yields `"Generate a short git branch
/// name…"`.
pub fn build_branch_name_prompt(context: &BranchNameWorkContext, custom_prompt: &str) -> String {
    let mut sections: Vec<String> = Vec::new();
    let prompt = js_trim(custom_prompt);
    if !prompt.is_empty() {
        sections.push(prompt.to_string());
        sections.push(String::new());
    }
    sections.push(
        if prompt.is_empty() {
            "Generate a short git branch name that summarizes the coding task described below."
        } else {
            "Generate a git branch name that summarizes the coding task described below."
        }
        .to_string(),
    );
    sections.push("Output ONLY the branch name on a single line, nothing else.".to_string());
    sections.push(String::new());
    sections.push("User request:".to_string());
    sections.push(js_trim(context.first_prompt).to_string());
    let assistant = context.assistant_message.map(js_trim).unwrap_or("");
    if !assistant.is_empty() {
        sections.push(String::new());
        sections.push("Agent's initial response:".to_string());
        sections.push(assistant.to_string());
    }
    sections.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::marine_creatures::MARINE_CREATURES;

    // ---- Oracle: sanitizeBranchSlug (branch-name-from-work.test.ts:10-31) ----

    #[test]
    fn sanitize_lowercases_and_kebab_cases() {
        assert_eq!(
            sanitize_branch_slug("Fix the auth bug", 4),
            "fix-the-auth-bug"
        );
    }

    #[test]
    fn sanitize_caps_at_four_words() {
        assert_eq!(
            sanitize_branch_slug("add dark mode toggle to settings page", 4),
            "add-dark-mode-toggle"
        );
    }

    #[test]
    fn sanitize_honors_a_custom_word_cap() {
        assert_eq!(sanitize_branch_slug("add dark mode toggle", 2), "add-dark");
    }

    #[test]
    fn sanitize_collapses_punctuation_quotes_slashes() {
        assert_eq!(
            sanitize_branch_slug("\"feat/login_flow!!\"", 4),
            "feat-login-flow"
        );
    }

    #[test]
    fn sanitize_returns_empty_when_nothing_usable() {
        assert_eq!(sanitize_branch_slug("   !!! ___ ", 4), "");
        assert_eq!(sanitize_branch_slug("", 4), "");
    }

    // ---- C1 pins (Codex): full char::to_lowercase, NOT to_ascii_lowercase ----

    /// `"İ".toLowerCase()` = `i` + U+0307 → the ASCII filter keeps `i`. A
    /// `to_ascii_lowercase` port leaves `İ`, which the whitelist drops → `""`.
    #[test]
    fn c1_sanitize_dotted_capital_i() {
        assert_eq!(sanitize_branch_slug("İ", 4), "i");
    }

    /// U+212A KELVIN SIGN lowercases to ASCII `k`.
    #[test]
    fn c1_sanitize_kelvin_sign() {
        assert_eq!(sanitize_branch_slug("\u{212A}", 4), "k");
    }

    // ---- Oracle: isAutoGeneratedCreatureBranchName (:33-49) ----

    #[test]
    fn creature_matches_case_insensitively() {
        assert!(is_auto_generated_creature_branch_name("Nautilus"));
        assert!(is_auto_generated_creature_branch_name("octopus"));
    }

    #[test]
    fn creature_matches_numbered_collision_variants() {
        assert!(is_auto_generated_creature_branch_name("Nautilus-2"));
        assert!(is_auto_generated_creature_branch_name("Seahorse-17"));
    }

    #[test]
    fn creature_rejects_user_and_work_derived_names() {
        assert!(!is_auto_generated_creature_branch_name("fix-auth-bug"));
        assert!(!is_auto_generated_creature_branch_name("my-feature"));
        assert!(!is_auto_generated_creature_branch_name(""));
    }

    // ---- C5 pins: corpus size + membership ----

    #[test]
    fn c5_marine_creatures_len_is_552() {
        assert_eq!(MARINE_CREATURES.len(), 552);
    }

    #[test]
    fn c5_membership_first_last_and_mythological() {
        assert!(is_auto_generated_creature_branch_name("nautilus")); // first entry
        assert!(is_auto_generated_creature_branch_name("hraesvelg")); // last entry
        assert!(is_auto_generated_creature_branch_name("kraken")); // mythological section
        assert!(!is_auto_generated_creature_branch_name("kubernetes")); // not a creature
    }

    // ---- Oracle: stripConfiguredBranchPrefix (:51-83) ----

    #[test]
    fn strip_prefix_strips_leaked_username() {
        assert_eq!(
            strip_configured_branch_prefix("tmchow-worktree-creation-spinner", Some("tmchow")),
            "worktree-creation-spinner"
        );
    }

    #[test]
    fn strip_prefix_multi_token() {
        assert_eq!(
            strip_configured_branch_prefix("my-team-add-logout", Some("my-team")),
            "add-logout"
        );
    }

    #[test]
    fn strip_prefix_normalizes_the_prefix() {
        assert_eq!(
            strip_configured_branch_prefix("jane-doe-fix-auth", Some("Jane.Doe")),
            "fix-auth"
        );
    }

    #[test]
    fn strip_prefix_leaves_a_real_leading_word() {
        assert_eq!(
            strip_configured_branch_prefix("add-logout-button", Some("tmchow")),
            "add-logout-button"
        );
    }

    #[test]
    fn strip_prefix_no_prefix_configured() {
        assert_eq!(
            strip_configured_branch_prefix("tmchow-fix-auth", None),
            "tmchow-fix-auth"
        );
        assert_eq!(
            strip_configured_branch_prefix("tmchow-fix-auth", Some("")),
            "tmchow-fix-auth"
        );
    }

    #[test]
    fn strip_prefix_only_output_returns_empty() {
        assert_eq!(strip_configured_branch_prefix("tmchow", Some("tmchow")), "");
        assert_eq!(
            strip_configured_branch_prefix("tmchow-fix-auth", Some("tmchow")),
            "fix-auth"
        );
    }

    // ---- Oracle: humanizeBranchSlug (:85-94) ----

    #[test]
    fn humanize_turns_kebab_into_label() {
        assert_eq!(
            humanize_branch_slug("supported-models-list"),
            "Supported models list"
        );
        assert_eq!(humanize_branch_slug("fix-auth"), "Fix auth");
    }

    #[test]
    fn humanize_empty_slug() {
        assert_eq!(humanize_branch_slug(""), "");
    }

    // ---- Oracle: buildBranchNamePrompt (:96-134) ----

    #[test]
    fn prompt_includes_user_prompt_omits_absent_assistant() {
        let ctx = BranchNameWorkContext {
            first_prompt: "Add a logout button",
            assistant_message: None,
        };
        let p = build_branch_name_prompt(&ctx, "");
        assert!(p.contains("Add a logout button"));
        assert!(!p.contains("Agent's initial response"));
    }

    #[test]
    fn prompt_default_wording_general_without_rules() {
        let ctx = BranchNameWorkContext {
            first_prompt: "Add a logout button",
            assistant_message: None,
        };
        let p = build_branch_name_prompt(&ctx, "");
        assert_eq!(
            p,
            "Generate a short git branch name that summarizes the coding task described below.\n\
             Output ONLY the branch name on a single line, nothing else.\n\
             \n\
             User request:\n\
             Add a logout button"
        );
        assert!(p.contains("Generate a short git branch name"));
        assert!(!p.contains("Rules:"));
    }

    #[test]
    fn prompt_includes_assistant_when_present() {
        let ctx = BranchNameWorkContext {
            first_prompt: "Add a logout button",
            assistant_message: Some("I'll wire it into the header."),
        };
        let p = build_branch_name_prompt(&ctx, "");
        assert!(p.contains("Agent's initial response"));
        assert!(p.contains("I'll wire it into the header."));
    }

    #[test]
    fn prompt_leads_with_custom_prompt_and_general_wording() {
        let ctx = BranchNameWorkContext {
            first_prompt: "Add a logout button",
            assistant_message: None,
        };
        let p = build_branch_name_prompt(&ctx, "Prefer product nouns.");
        assert!(p.starts_with("Prefer product nouns."));
        assert!(!p.contains("Additional user prompt:"));
        assert!(!p.contains("Rules:"));
        // Custom prompt → "Generate a git branch name" (no "short").
        assert!(p.contains("Generate a git branch name"));
        assert!(!p.contains("Generate a short git branch name"));
        assert!(p.contains("Output ONLY the branch name on a single line"));
        assert!(p.contains("Add a logout button"));
    }
}
